// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
import { Schema, Types } from "mongoose";

export interface ICar {
  company: Types.ObjectId,
  name: string,
  wheelSize: number,
  engine: {
    horsepower: string,
    cylinder: number,
    identification: {
      manufacturer: string,
      serialNumber: string,
    }
  }
}

const carsSchema = new Schema<ICar>({
  company: { type: Schema.Types.ObjectId, ref: 'companies' },
  name: { type: String, required: true },
  wheelSize: { type: Number, required: true },
  engine: {
    horsepower: String,
    cylinder: Number,
    identification: {
      manufacturer: String,
      serialNumber: String,
    }
  }
}, {
  timestamps: false,
});

export default carsSchema;
