// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
import { Schema, Types } from "mongoose";

export interface ICompany {
  addresses?: Types.ObjectId[],
  name?: string,
}

const companiesSchema =  new Schema<ICompany>({
  addresses: [{ type: Schema.Types.ObjectId, ref: 'addresses' }],
  name: { type: String, required: true },
}, {
  timestamps: false,
});

export default companiesSchema;
